### ISSUE TITLE
Fails to build using gcc 7.5 due to ASAN check

### ISSUE THREAD

**Issue by TimWolla** [vtest/VTest#27]
```
lib/vtcp.c: In function ‘VTCP_Check’:
lib/vtcp.c:632:43: error: missing binary operator before token "("
 #if (defined(__SANITIZER) || __has_feature(address_sanitizer))
                                           ^
```

Full reproducer:

```
$ sed -i 's/-Werror//' Makefile
$ make
awk -f src/gensequences src/sequences > src/teken_state.h
trying python3
cc \
	-O2 -s -Wall  \
	-o vtest \
	-Isrc -Ilib -I/usr/local/include -pthread \
	src/*.c lib/*.c \
	-L/usr/local/lib -lm -lpcre -lz
src/vtc_main.c: In function ‘cleaner_setup’:
src/vtc_main.c:238:3: warning: ignoring return value of ‘nice’, declared with attribute warn_unused_result [-Wunused-result]
   (void)nice(1);  /* Not important */
   ^~~~~~~~~~~~~
lib/vtcp.c: In function ‘VTCP_Check’:
lib/vtcp.c:632:43: error: missing binary operator before token "("
 #if (defined(__SANITIZER) || __has_feature(address_sanitizer))
                                           ^
Makefile:37: recipe for target 'vtest' failed
make: *** [vtest] Error 1
$ cc --version
cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

see also: https://github.com/TimWolla/action-install-haproxy/runs/2545203587?check_suite_focus=true#step:3:1193

**Comment by haproxyFred** [comment]
I have just created a PR for this issue:

https://github.com/vtest/VTest/pull/28

**Comment by TimWolla** [comment]
Thanks, I can confirm it now works for me.
